version: 2

project_name: genenv

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    binary: genenv
    ldflags:
      - -s -w

archives:
  - formats: [ "binary" ]
    name_template: >-
      {{ .ProjectName }}-
      {{- .Os | tolower }}-
      {{- .Arch | tolower }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

checksum:
  name_template: "checksums.txt"
